[package]
name = "once_3dm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_io = { git = "https://github.com/julionce/once_io" }