[package]
name = "once_3dm_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = {version = "1.0", features = ["parsing", "full"]}
quote = "1.0"